services:
  - type: web
    name: sdwb2-movie-bot
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m bot
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_CHANNEL
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: URL
        sync: false
      - key: ADMIN_PASSWORD
        value: admin123
      - key: TMDB_API_KEY
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: UPDATE_CHANNEL
        value: sdmoviepointes
      - key: VALIDITY
        value: "2592000,7776000,15552000"
      - key: AUTO_DELETE
        value: "True"
      - key: AUTO_DELETE_TIME
        value: "300"
      - key: SHORTENER_API
        sync: false
      - key: SHORTENER_SITE
        sync: false
      - key: RESULTS_HOW_TO_DOWNLOAD_LINK
        sync: false
      - key: REQUEST_MOVIE_URL
        sync: false
      - key: PORT
        value: "8080"
